#!/bin/sh

NAME=cifs-rdma
VERSION=1.0

set -e

case "$1" in
  configure)
    sudo dkms install -m $NAME -v $VERSION
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

exit 0
